FROM ubuntu:xenial

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libcurl4-openssl-dev python-pip libboost-python-dev libgtk2.0-dev && \
    rm -rf /var/lib/apt/lists/* 

COPY /build/requirements.txt ./
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install tornado==4.5.3 trollius && \
    pip install -U youtube-dl

ADD /app/ .

# Expose the port
EXPOSE 80

ENTRYPOINT [ "python", "-u", "./main.py" ]